---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-hdd"
  labels:
      type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "1Ti"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/sdb/media"
---
