## media.transmission-openvpn.values.yml
## helm
replicaCount: 1

image:
    repository: "haugene/transmission-openvpn"
    tag: "latest" # Suffixed by -armhf to pull the ARM image
    pullPolicy: "IfNotPresent"

dnsConfig:
  nameservers:
    - 1.1.1.1
    - 8.8.8.8

env:
    - name: OPENVPN_PROVIDER
      value: "NORDVPN" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
    - name: OPENVPN_USERNAME
      valueFrom: # Reference to the secret | openvpn.username
        secretKeyRef:
          name: "openvpn"
          key: "username"
    - name: OPENVPN_PASSWORD
      valueFrom: # Reference to the secret | openvpn.password
        secretKeyRef:
          name: "openvpn"
          key: "password"
    - name: NORDVPN_PROTOCOL
      value: "TCP"
    - name: NORDVPN_COUNTRY
      value: "PL" # Country where we want to download over VPN
    - name: NORDVPN_CATEGORY
      value: "P2P" # VPN Type
    - name: LOCAL_NETWORK
      value: "192.168.0.0/24"
    - name: TRANSMISSION_PEER_PORT
      value: "47444"
    - name: TRANSMISSION_DOWNLOAD_DIR
      value: "/downloads/torrents/transmission"
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"

service:
   type: ClusterIP
   port: 80

volumes:
  - name: media-hdd
    persistentVolumeClaim:
      claimName: media-hdd
  - name: dev-tun
    hostPath:
      path: /dev/net/tun

volumeMounts:
  - name: media-hdd
    mountPath: /data
    subPath: configs/transmission-data
  - name: media-hdd
    mountPath: /downloads/torrents
    subPath: downloads/torrents
  - name: media-hdd
    mountPath: /config
    subPath: configs/transmission-data

securityContext:
  capabilities:
    add:
      - NET_ADMIN
