---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "media-services"
  name: "media-hdd"
spec:
  storageClassName: "manual"
  accessModes: 
    - ReadWriteMany
  resources:
     requests:
        storage: "1Ti"
---
